linters:
  disable-all: true
  enable:
    #- depguard # useful for Sirupsen and old mgo
    # Suggests code refactoring
    #- govet
    - staticcheck # aka megacheck, supercedes govet
    #- goconst
    - ineffassign
    #- maligned
    #- prealloc
    #- gosimple
    # Finds unused and dead code
    - unused
    # - structcheck
    - varcheck
    - deadcode
    # - unparam
    # Style changes
    - golint
    # - goimports # supercedes gofmt
    - misspell
    #- lll

issues:
  exclude:
    # https://github.com/golangci/golangci-lint/issues/446
    - composites
