linters:
  disable-all: true
  enable:
    - govet
    #- staticcheck # aka megacheck, replaces govet
    #- depguard # useful for Sirupsen and old mgo
    # Suggests code refactoring
    - goconst
    - ineffassign
    #- maligned
    #- prealloc
    #- gosimple
    # Finds unused and dead code
    #- unused
    #- structcheck
    #- varcheck
    #- deadcodde
    #- unparam
    # Style changes
    - golint
    # - goimports # replaces gofmt
    - misspell
    #- lll

issues:
  exclude:
    # https://github.com/golangci/golangci-lint/issues/446
    - composites
