MongoDB:
    # See https://docs.mongodb.com/manual/reference/connection-string/
    ConnectionString: mongodb://localhost:27017
    # Example with authentication. Be sure to change the AuthenticationMechanism as well.
    # ConnectionString: mongodb://username:password@localhost:27017

    # Accepted Values: null, "SCRAM-SHA-1", "MONGODB-CR", "PLAIN"
    # Since Mongo version 3.0 the default authentication mechanism is SCRAM-SHA-1
    AuthenticationMechanism: null

    # The time in hours before RITA's connection to MongoDB times out. 0 waits indefinitely.
    SocketTimeout: 2

    # For encrypting data on the wire between RITA and MongoDB
    TLS:
        Enable: false
        #If set, RITA will verify the MongoDB certificate's hostname and validity
        VerifyCertificate: false
        #If set, RITA will use the provided CA file instead of the system's CA's
        CAFile: null

LogConfig:
    # LogLevel
    # 3 = debug
    # 2 = info
    # 1 = warn
    # 0 = error
    LogLevel: 2

    # LogPath is the path for Rita's logs. Make sure permissions are set accordingly.
    # Logs will only be written here if LogToFile is true
    RitaLogPath: /var/lib/rita/logs

    LogToFile: true
    LogToDB: true

# The section Bro configures the bro ingestor
Bro:
    # Path to a top level directory of log files
    ImportDirectory: /opt/bro/logs/

    # Files directly in the ImportDirectory will be imported into a database
    # given by DBRoot. Files in a subfolder of ImportDirectory will be imported
    # into DBRoot-$SUBFOLDER_NAME.
    DBRoot: "RITA"

    # This database holds information about the procesed files and databases.
    MetaDB: MetaDatabase

    # The number of records shipped off to MongoDB at a time. Increasing
    # the size of the buffer will improve import timings but will leave more
    # records unimported if there is an error
    ImportBuffer: 100000

BlackListed:
    # These are blacklists built into rita-blacklist. Set these to false
    # to disable checks against them.
    myIP.ms: true
    MalwareDomains.com: true
    MalwareDomainList.com: true

    # Google SafeBrowsing requires an api key and a file to cache the results in.
    # If either APIKey or Database is an empty string, Google SafeBrowsing will
    # not be queried.
    SafeBrowsing:
        APIKey: ""
        Database: /var/lib/rita/safebrowsing

    # These are custom blacklists that you may define. They are lists of either
    # file paths or urls. These custom blacklists are expected to be simple,
    # line separated text documents containing a list of blacklisted entries.

    # Example: CustomIPBlacklists: ["$HOME/.rita/myIPBlacklist.txt"]
    # myIPBlacklist.txt would look like this:
    # 192.168.0.1
    # 10.10.174.1

    # Lists containing both IPv4 and IPv6 addresses are acceptable
    CustomIPBlacklists: []
    # Lists containing hostnames, domain names, and FQDNs are acceptable
    CustomHostnameBlacklists: []
    # URLs must each contain a protocol, a host, and a resource
    # Ex: http://google.com/
    # Ex: ftp://myftpserver.com/a/file/over/here.txt
    CustomURLBlacklists: []

Crossref:
    BeaconThreshold: .7

Scanning:
    ScanThreshold: 50

Beacon:
    DefaultConnectionThresh: 24

# Adjusting batchsize and prefetch may help speed up certain database queries
BatchSize: 300
Prefetch: 0.33
