package beacon

import (
	dataBeacon "github.com/activecm/rita/datatypes/beacon"
	"gopkg.in/mgo.v2/bson"
)

var writerTestDataList = []dataBeacon.BeaconAnalysisOutput{
	dataBeacon.BeaconAnalysisOutput{
		UconnID:           bson.NewObjectId(),
		TS_iRange:         1,
		TS_iMode:          1,
		TS_iModeCount:     1,
		TS_intervals:      []int64{1, 1},
		TS_intervalCounts: []int64{1, 1},
		TS_iDispersion:    1,
		TS_iSkew:          1.5,
		TS_duration:       1.5,
		TS_score:          1.5,
		DS_range:          1,
		DS_mode:           1,
		DS_modeCount:      1,
		DS_sizes:          []int64{1, 1},
		DS_sizeCounts:     []int64{1, 1},
		DS_dispersion:     1,
		DS_skew:           1.5,
		DS_score:          1.5,
		Score:             1.5,
	},
	dataBeacon.BeaconAnalysisOutput{
		UconnID:           bson.NewObjectId(),
		TS_iRange:         2,
		TS_iMode:          2,
		TS_iModeCount:     2,
		TS_intervals:      []int64{2, 2},
		TS_intervalCounts: []int64{2, 2},
		TS_iDispersion:    2,
		TS_iSkew:          2.5,
		TS_duration:       2.5,
		TS_score:          2.5,
		DS_range:          2,
		DS_mode:           2,
		DS_modeCount:      2,
		DS_sizes:          []int64{2, 2},
		DS_sizeCounts:     []int64{2, 2},
		DS_dispersion:     2,
		DS_skew:           2.5,
		DS_score:          2.5,
		Score:             2.5,
	},
	dataBeacon.BeaconAnalysisOutput{
		UconnID:           bson.NewObjectId(),
		TS_iRange:         3,
		TS_iMode:          3,
		TS_iModeCount:     3,
		TS_intervals:      []int64{3, 3},
		TS_intervalCounts: []int64{3, 3},
		TS_iDispersion:    3,
		TS_iSkew:          3.5,
		TS_duration:       3.5,
		TS_score:          3.5,
		DS_range:          3,
		DS_mode:           3,
		DS_modeCount:      3,
		DS_sizes:          []int64{3, 3},
		DS_sizeCounts:     []int64{3, 3},
		DS_dispersion:     3,
		DS_skew:           3.5,
		DS_score:          3.5,
		Score:             3.5,
	},
}
