package beacon

import (
	"github.com/activecm/rita/datatypes/beacon"
	"github.com/globalsign/mgo/bson"
)

var writerTestDataList = []beacon.AnalysisOutput{
	beacon.AnalysisOutput{
		UconnID:          bson.NewObjectId(),
		Src:              "0.0.0.0",
		Dst:              "0.0.0.0",
		TSIRange:         1,
		TSIMode:          1,
		TSIModeCount:     1,
		TSIntervals:      []int64{1, 1},
		TSIntervalCounts: []int64{1, 1},
		TSIDispersion:    1,
		TSISkew:          1.5,
		TSDuration:       1.5,
		TSScore:          1.5,
		DSRange:          1,
		DSMode:           1,
		DSModeCount:      1,
		DSSizes:          []int64{1, 1},
		DSSizeCounts:     []int64{1, 1},
		DSDispersion:     1,
		DSSkew:           1.5,
		DSScore:          1.5,
		Score:            1.5,
	},
	beacon.AnalysisOutput{
		UconnID:          bson.NewObjectId(),
		Src:              "0.0.0.0",
		Dst:              "0.0.0.0",
		TSIRange:         2,
		TSIMode:          2,
		TSIModeCount:     2,
		TSIntervals:      []int64{2, 2},
		TSIntervalCounts: []int64{2, 2},
		TSIDispersion:    2,
		TSISkew:          2.5,
		TSDuration:       2.5,
		TSScore:          2.5,
		DSRange:          2,
		DSMode:           2,
		DSModeCount:      2,
		DSSizes:          []int64{2, 2},
		DSSizeCounts:     []int64{2, 2},
		DSDispersion:     2,
		DSSkew:           2.5,
		DSScore:          2.5,
		Score:            2.5,
	},
	beacon.AnalysisOutput{
		UconnID:          bson.NewObjectId(),
		Src:              "0.0.0.0",
		Dst:              "0.0.0.0",
		TSIRange:         3,
		TSIMode:          3,
		TSIModeCount:     3,
		TSIntervals:      []int64{3, 3},
		TSIntervalCounts: []int64{3, 3},
		TSIDispersion:    3,
		TSISkew:          3.5,
		TSDuration:       3.5,
		TSScore:          3.5,
		DSRange:          3,
		DSMode:           3,
		DSModeCount:      3,
		DSSizes:          []int64{3, 3},
		DSSizeCounts:     []int64{3, 3},
		DSDispersion:     3,
		DSSkew:           3.5,
		DSScore:          3.5,
		Score:            3.5,
	},
}
