name: Run rita tests

on:
  pull_request:
    # Run tests except if only markdown files are changed
    paths:
      - '*'
      - '!*.md'

jobs:
  test:
    name: static and unit tests
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - run: make docker-test

  integration:
    name: integration tests
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          make docker-build
          docker container create --name rita quay.io/activecm/rita:latest
          docker cp rita:/rita ./rita
          mkdir vendor
      - run: make integration-test
